FE/.babelrc, FE/.eslintrc, FE/.gitignore, FE/.prettierrc.json, FE/config/webpack.config.js, FE/config/webpack.dev.js, FE/config/webpack.prod.js, FE/cypress.config.ts, FE/cypress/e2e/login.cy.ts, FE/cypress/fixtures/example.json, FE/cypress/support/commands.ts, FE/cypress/support/e2e.ts, FE/cypress/tsconfig.json, FE/jest.config.ts, FE/package-lock.json, FE/package.json, FE/public/index.html, FE/setupTest.ts, FE/src/App.tsx, FE/src/__tests__/__snapshots__/mainpage.test.tsx.snap, FE/src/__tests__/mainpage.test.tsx, FE/src/index.tsx, FE/src/pages/LoginPage.tsx, FE/src/pages/MainPage.tsx, FE/src/styles/Main.module.scss, FE/src/styles/global.d.ts, FE/tsconfig.jest.json, FE/tsconfig.json
=> [FE] 프론트 프로젝트 환경 설정

BE/src/main/java/com/newsainturtle/shadowmate/auth/constant/AuthConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/auth/controller/AuthController.java, BE/src/main/java/com/newsainturtle/shadowmate/auth/dto/CertifyEmailRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/auth/exception/AuthErrorResult.java, BE/src/main/java/com/newsainturtle/shadowmate/auth/exception/AuthException.java, BE/src/main/java/com/newsainturtle/shadowmate/auth/service/AuthService.java, BE/src/main/java/com/newsainturtle/shadowmate/auth/service/AuthServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/common/BaseResponse.java, BE/src/main/java/com/newsainturtle/shadowmate/common/GlobalExceptionHandler.java, BE/src/main/java/com/newsainturtle/shadowmate/user/entity/User.java, BE/src/main/java/com/newsainturtle/shadowmate/user/enums/PlannerAccessScope.java, BE/src/main/java/com/newsainturtle/shadowmate/user/repository/UserRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserService.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/auth/AuthControlloerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/auth/AuthServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/auth/UserRepositoryTest.java
=> [BE] 이메일 중복 검사 및 인증 API 생성

BE/build.gradle, BE/src/main/java/com/newsainturtle/shadowmate/auth/exception/AuthErrorResult.java, BE/src/main/java/com/newsainturtle/shadowmate/auth/service/AuthServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/config/SecurityConfig.java, BE/src/main/java/com/newsainturtle/shadowmate/user/entity/User.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/auth/AuthServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/auth/AuthControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/auth/AuthServiceTest.java
=> [BE] 메일로 인증번호 전송

BE/src/main/java/com/newsainturtle/shadowmate/auth/constant/AuthConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/auth/controller/AuthController.java, BE/src/main/java/com/newsainturtle/shadowmate/auth/dto/JoinRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/auth/service/AuthService.java, BE/src/main/java/com/newsainturtle/shadowmate/auth/service/AuthServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/auth/AuthControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/auth/AuthServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/auth/UserRepositoryTest.java
=> [BE] 회원가입 API 생성

BE/src/main/java/com/newsainturtle/shadowmate/ShadowmateApplication.java, BE/src/main/java/com/newsainturtle/shadowmate/common/entity/CommonEntity.java, BE/src/main/java/com/newsainturtle/shadowmate/config/jwt/JwtProvider.java, BE/src/main/java/com/newsainturtle/shadowmate/user/entity/User.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/auth/AuthServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/auth/UserRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/auth/AuthServiceTest.java
=> [BE] 공통 부모 엔티티 생성

BE/src/main/java/com/newsainturtle/shadowmate/common/GlobalExceptionHandler.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/constant/PlannerSettingConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/controller/PlannerSettingController.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/dto/AddCategoryRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/entity/Category.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/entity/CategoryColor.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/exception/PlannerSettingErrorResult.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/exception/PlannerSettingException.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/repository/CategoryColorRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/repository/CategoryRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingService.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/CategoryRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/CategoryServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingServiceTest.java
=> [BE] 카테고리 등록 API 작성

BE/src/main/java/com/newsainturtle/shadowmate/auth/constant/AuthConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/auth/controller/AuthController.java, BE/src/main/java/com/newsainturtle/shadowmate/auth/dto/DuplicatedNicknameRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/auth/exception/AuthErrorResult.java, BE/src/main/java/com/newsainturtle/shadowmate/auth/service/AuthService.java, BE/src/main/java/com/newsainturtle/shadowmate/auth/service/AuthServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/user/repository/UserRepository.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/auth/AuthControlloerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/auth/AuthServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/auth/UserRepositoryTest.java
=> [BE] 닉네임 중복검사

BE/src/main/java/com/newsainturtle/shadowmate/auth/service/AuthServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/user/entity/User.java, BE/src/main/java/com/newsainturtle/shadowmate/user/enums/SocialType.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/auth/AuthControlloerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/auth/AuthServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/auth/UserRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/auth/AuthServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/auth/UserRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/CategoryRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingServiceTest.java
=> [BE] UserEntity 소셜로그인기능 수정

BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/constant/PlannerSettingConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/controller/PlannerSettingController.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/dto/GetCategoryColorListResponse.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingService.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/CategoryColorRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingServiceTest.java
=> [BE] 카테고리 색상 목록 조회 API 작성

FE/src/components/common/Button/index.tsx, FE/src/components/common/FriendProfile/index.tsx, FE/src/components/common/Profile/index.tsx, FE/src/pages/commonPage.tsx, FE/src/styles/common/Profile.module.scss
close #23 
- 친구 프로필 CSS 수정 및 내 프로필 컴포넌트 생성 추가
- 컴포넌트 onClick 적용 ( rest 추가)
=> [FE] 공통 컴포넌트 수정

BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/constant/PlannerSettingConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/controller/PlannerSettingController.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/dto/GetCategoryListResponse.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/dto/GetCategoryResponse.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/repository/CategoryRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingService.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/CategoryRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingServiceTest.java
=> [BE] 카테고리 목록 조회 API 작성

BE/src/main/java/com/newsainturtle/shadowmate/auth/exception/AuthErrorResult.java, BE/src/main/java/com/newsainturtle/shadowmate/common/BaseErrorResult.java, BE/src/main/java/com/newsainturtle/shadowmate/common/GlobalExceptionHandler.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/exception/PlannerSettingErrorResult.java, BE/src/main/java/com/newsainturtle/shadowmate/user/constant/UserConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/user/controller/UserController.java, BE/src/main/java/com/newsainturtle/shadowmate/user/dto/ProfileResponse.java, BE/src/main/java/com/newsainturtle/shadowmate/user/exception/UserErrorResult.java, BE/src/main/java/com/newsainturtle/shadowmate/user/exception/UserException.java, BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserService.java, BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserServiceTest.java
=> [BE] 마이페이지 프로필 조회 API 작성

BE/src/main/java/com/newsainturtle/shadowmate/auth/exception/AuthErrorResult.java, BE/src/main/java/com/newsainturtle/shadowmate/auth/service/AuthService.java, BE/src/main/java/com/newsainturtle/shadowmate/auth/service/AuthServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/constant/PlannerSettingConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/controller/PlannerSettingController.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/dto/SetAccessScopeRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/exception/PlannerSettingErrorResult.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingService.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/user/enums/PlannerAccessScope.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/auth/AuthServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/UserRepositoryTest.java
=> [BE] 플래너 공개여부 API 작성

BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/controller/PlannerSettingController.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/exception/PlannerSettingErrorResult.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingService.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingServiceTest.java
close #50
- 용자 인증 함수 사용하여 코드 리팩터링
=> [BE] 사용자 인증 함수 사용하여 코드 리팩터링

BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/constant/PlannerSettingConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/controller/PlannerSettingController.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/dto/UpdateCategoryRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/exception/PlannerSettingErrorResult.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingService.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/CategoryRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingServiceTest.java
close #54
- 카테고리 수정 API 작성
- 중복 코드는 함수 생성해서 재사용했습니다~
=> [BE] 카테고리 수정 API 작성

BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/constant/PlannerSettingConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/controller/PlannerSettingController.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/dto/GetDdayListResponse.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/dto/GetDdayResponse.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/repository/DdayRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingService.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/DdayRepositoryTest.java
close #66
- 디데이 목록 조회 API 작성
- 테스트 코드 기능별로 내부 클래스로 묶음
=> [BE] 디데이 목록 조회 API 작성

BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/constant/PlannerSettingConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/controller/PlannerSettingController.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/dto/RemoveDdayRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/repository/DdayRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingService.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/DdayRepositoryTest.java
=> [BE] 디데이 삭제 API 작성

BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/constant/PlannerSettingConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/controller/PlannerSettingController.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/dto/AddDdayRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/dto/UpdateDdayRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/exception/PlannerSettingErrorResult.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/repository/DdayRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingService.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/DdayRepositoryTest.java
close #70
- 디데이 수정 테스트 코드 작성
- 디데이 수정 API 작성
=> [BE] 디데이 수정 API 작성

BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/controller/PlannerSettingController.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/dto/AddCategoryResponse.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/dto/AddDdayResponse.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/repository/CategoryRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/repository/DdayRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingService.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingServiceTest.java
close #72
1. 데이터 생성 시 response 수정
2. 레포지토리에서 데이터 검색시 User 추가
=> [BE] 플래너 설정 코드 수정 + 리팩토링

FE/config/webpack.config.js, FE/src/App.scss, FE/src/components/common/Header/Menu.tsx, FE/src/components/planner/week/Week.module.scss, FE/src/components/planner/week/Week.tsx, FE/src/components/planner/week/WeekItem.tsx, FE/src/components/planner/week/WeekTodo.tsx, FE/src/pages/Planner/WeekPage.tsx, FE/src/pages/commonPage.tsx, FE/src/styles/auth/Login.module.scss, FE/src/util/getThisWeek.ts
close #61 
- 주별 컴포넌트 생성 및 배치
- App.scss 스크롤바 스타일 html, body -> * (전역) 으로 변경
- Login.module.scss -> line-height 스타일 필요 없어서 삭제
- Menu.tsx key값 없어서 에러 뜨길래 key 추가
- scss 에서 debug 하기 위해 webpack 수정  
: @debug "출력할 String 값 #{$변수} ";
- 이번주 날짜 구하는 함수 생성
=> [FE] 주별 페이지 컴포넌트 생성 및 배치

BE/src/main/java/com/newsainturtle/shadowmate/common/GlobalExceptionHandler.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/constant/PlannerConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/controller/PlannerController.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/AddDailyTodoRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/AddDailyTodoResponse.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/UpdateTodayGoalRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/UpdateTomorrowGoalRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/DailyPlanner.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/Todo.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/enums/TodoStatus.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/exception/PlannerErrorResult.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/exception/PlannerException.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/DailyPlannerRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/TodoRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerService.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/DailyPlannerServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/PlannerControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/DailyPlannerRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/TodoRepositoryTest.java
=> [BE] 내일의 다짐 편집 API 작성

FE/src/components/planner/week/Week.module.scss, FE/src/components/planner/week/WeekItem.tsx, FE/src/components/planner/week/WeekTodo.tsx
close #
- 중간에 브랜치명을 변경했더니, 변경 안된 상태로 커밋되어 버려서 ,,, 두 브랜치 병합하려고 pr 함.
=> [FE] feature/front-issue84 리뷰 해결 브랜치 병합

BE/src/main/java/com/newsainturtle/shadowmate/planner/constant/PlannerConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/controller/PlannerController.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/AddDailyLikeRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/DailyPlannerLike.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/exception/PlannerErrorResult.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/DailyPlannerLikeRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/DailyPlannerRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerService.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/DailyPlannerServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/PlannerControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/DailyPlannerLikeRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/DailyPlannerRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/TodoRepositoryTest.java
=> [BE] 좋아요 등록 API 작성

BE/src/main/java/com/newsainturtle/shadowmate/planner/constant/PlannerConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/controller/PlannerController.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/AddDailyLikeRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/RemoveDailyLikeRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/DailyPlannerLike.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/exception/PlannerErrorResult.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/DailyPlannerLikeRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/DailyPlannerRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerService.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/DailyPlannerServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/PlannerControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/DailyPlannerLikeRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/DailyPlannerRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/TodoRepositoryTest.java
=> [BE] 좋아요 취소 API 작성

BE/src/main/java/com/newsainturtle/shadowmate/planner/constant/PlannerConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/controller/PlannerController.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/AddDailyLikeRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/RemoveDailyLikeRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/RemoveDailyTodoRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/DailyPlannerLike.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/exception/PlannerErrorResult.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/DailyPlannerLikeRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/DailyPlannerRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/TodoRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerService.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/DailyPlannerServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/PlannerControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/DailyPlannerLikeRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/DailyPlannerRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/TodoRepositoryTest.java
close #96 
- 일일 플래너 할일 삭제 API 작성
=> [BE] 일일 플래너 할일 삭제 API 작성

BE/src/main/java/com/newsainturtle/shadowmate/planner/constant/PlannerConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/controller/PlannerController.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/UpdateRetrospectionRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerService.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/DailyPlannerServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/PlannerControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/DailyPlannerRepositoryTest.java
=> [BE] 오늘의 회고 편집 API 작성

BE/src/main/java/com/newsainturtle/shadowmate/planner/controller/PlannerController.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerServiceImpl.java
close #106
- 충돌 해결할 때 발생한 코드 오류 수정
=> [BE] 코드 오류 수정

BE/src/main/java/com/newsainturtle/shadowmate/planner/constant/PlannerConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/controller/PlannerController.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/UpdateRetrospectionImageRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerService.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/DailyPlannerServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/PlannerControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/DailyPlannerRepositoryTest.java
close #105
- 오늘의 회고 사진 업로드 API 작성
=> [BE] 오늘의 회고 사진 업로드 API 작성

BE/src/main/java/com/newsainturtle/shadowmate/planner/constant/PlannerConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/controller/PlannerController.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/UpdateDailyTodoRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/enums/TodoStatus.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/exception/PlannerErrorResult.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/TodoRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerService.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/DailyPlannerServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/PlannerControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/DailyPlannerLikeRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/TodoRepositoryTest.java
close #109
- 일일 플래너 할일 수정 API 작성
=> [BE] 일일 플래너 할일 수정 API 작성

BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/TodoRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/constant/PlannerSettingConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/controller/PlannerSettingController.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/dto/RemoveCategoryRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/repository/CategoryRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingService.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/CategoryRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/TodoRepositoryTest.java
close #63
- 카테고리 삭제 API 작성
- 카테고리 목록 조회 시 삭제된 카테고리 제외
=> [BE] 카테고리 삭제 API 작성

BE/src/main/java/com/newsainturtle/shadowmate/planner/constant/PlannerConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/controller/PlannerController.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/AddWeeklyTodoRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/AddWeeklyTodoResponse.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/Weekly.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/WeeklyTodo.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/exception/PlannerErrorResult.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/WeeklyRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/WeeklyTodoRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/WeeklyPlannerService.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/WeeklyPlannerServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/PlannerControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/WeeklyPlannerServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/WeeklyRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/WeeklyTodoRepositoryTest.java
=> [BE] 주차별 할일 등록 API 작성

BE/src/main/java/com/newsainturtle/shadowmate/common/GlobalExceptionHandler.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/constant/FollowConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/controller/FollowController.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/dto/FollowingResponse.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/entity/Follow.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/exception/FollowErrorResult.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/exception/FollowException.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/repository/FollowRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowService.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserRepositoryTest.java
=> [BE] 팔로잉 조회 API 작성

BE/src/main/java/com/newsainturtle/shadowmate/planner/constant/PlannerConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/controller/PlannerController.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/AddTimeTableRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/AddTimeTableResponse.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/TimeTable.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/exception/PlannerErrorResult.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/TimeTableRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerService.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/DailyPlannerServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/PlannerControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/TimeTableRepositoryTest.java
=> [BE] 타임 테이블 등록 API 작성

BE/src/main/java/com/newsainturtle/shadowmate/planner/constant/PlannerConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/controller/PlannerController.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/UpdateWeeklyTodoContentRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/TodoRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/WeeklyTodoRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/WeeklyPlannerService.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/WeeklyPlannerServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/DailyPlannerServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/PlannerControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/WeeklyPlannerServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/TodoRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/WeeklyTodoRepositoryTest.java
close #120
- 주차별 할일 내용 수정 API 작성
=> [BE] 주차별 할일 내용 수정 API 작성

BE/src/main/java/com/newsainturtle/shadowmate/planner/constant/PlannerConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/controller/PlannerController.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/RemoveTimeTableRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/exception/PlannerErrorResult.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/TimeTableRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerService.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/DailyPlannerServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/PlannerControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/TimeTableRepositoryTest.java
=> [BE] 타임 테이블 삭제 API 작성

BE/src/main/java/com/newsainturtle/shadowmate/follow/dto/FollowingResponse.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowServiceTest.java
=> [BE] 팔로잉 조회 API 리팩토링

BE/src/main/java/com/newsainturtle/shadowmate/planner/constant/PlannerConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/controller/PlannerController.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/UpdateWeeklyTodoStatusRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/WeeklyPlannerService.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/WeeklyPlannerServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/PlannerControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/WeeklyPlannerServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/WeeklyTodoRepositoryTest.java
close #131 
- 주차별 할일 상태 수정 API 작성
=> [BE] 주차별 할일 상태 수정 API 작성

BE/src/main/java/com/newsainturtle/shadowmate/follow/constant/FollowConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/controller/FollowController.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/dto/AddFollowRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/dto/AddFollowResponse.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/dto/FollowingResponse.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/entity/FollowRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/exception/FollowErrorResult.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/repository/FollowRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/repository/FollowRequestRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowService.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/repository/FollowRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/repository/FollowRequestRepositoryTest.java
=> [BE] 팔로우 신청 API 작성

FE/src/components/planner/day/Header.tsx, FE/src/components/planner/day/TodoItem.tsx, FE/src/components/planner/day/TodoList.tsx, FE/src/components/social/CardItem.tsx, FE/src/components/social/CardList.tsx, FE/src/components/social/SocialHeader.tsx, FE/src/pages/Planner/DayPage.tsx, FE/src/pages/SocialPage.tsx, FE/src/styles/planner/day.module.scss, FE/src/util/data/DayTodos.ts, FE/src/util/planner.interface.ts
close #103 
- 소셜 페이지 파일 경로 대소문자 수정(HMR error 해결)
- 일별 플래너 날짜 이동
- 할 일 하나만 추가하기
- 할 일 작성하는 부분 높이 크기 자동화
- 일일 플래너 할 일 추가 삭제 로직 주별 플래너과 비슷하게 수정
- 할 일 카테고리 선택 추가
=> [FE] 일별 플래너 일부 기능 추가 및 수정

FE/package-lock.json, FE/src/components/mypage/details/MyPageInfo.tsx, FE/src/styles/mypage/MyPage.module.scss, FE/src/util/data/MyInfoData.ts
close #101 
- package-lock.json에 emoji-picker-react 라이브러리 삭제
- 마이페이지 내 정보 수정 컴포넌트 생성 및 배치
=> [FE] 마이페이지 내 정보 수정 컴포넌트 생성 및 배치

BE/src/main/java/com/newsainturtle/shadowmate/planner/constant/PlannerConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/controller/PlannerController.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/RemoveWeeklyTodoRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/WeeklyTodoRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/WeeklyPlannerService.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/WeeklyPlannerServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/PlannerControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/WeeklyPlannerServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/WeeklyTodoRepositoryTest.java
close #141 
- 주차별 할일 삭제 API 작성
=> [BE] 주차별 할일 삭제 API 작성

FE/package-lock.json, FE/package.json, FE/src/components/common/Input/index.tsx, FE/src/components/mypage/MyPageDetail.tsx, FE/src/components/mypage/MyPageFrame.tsx, FE/src/components/mypage/MyPageList.tsx, FE/src/components/mypage/details/MyPageDday.tsx, FE/src/components/mypage/item/MyPageCategoryItem.tsx, FE/src/components/mypage/item/MyPageDdayItem.tsx, FE/src/styles/common/Input.module.scss, FE/src/styles/mypage/MyPage.module.scss, FE/src/util/data/DdayData.ts, FE/src/util/getThisWeek.ts
close #113 
- 디데이 생성
- 생성 시 클릭 이펙트 및 생성된 정보 보여줌.
- 디데이 수정
- 디데이 수정 시 타이틀 글자 수 2~20자 벗어날 경우, hypertext error 후 return 처리.
- 디데이 날짜 선택 라이브러리 (mui x / date calendar 사용) 설치 및 날짜 표시
- 카테고리, 디데이 목록 스크롤 생성
- 디데이 삭제 
- 디데이 날짜 출력 시 formatting 해주는 함수 정의
- 공통 컴포넌트 Input 에 error 프로퍼티 추가 
- 요일 출력 시 일요일 `undefined` 로 나오는 문제 수정
=> [FE] 마이페이지 디데이 생성, 수정 및 삭제 기능 구현

BE/src/main/java/com/newsainturtle/shadowmate/follow/constant/FollowConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/controller/FollowController.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/dto/FollowerResponse.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/dto/FollowingResponse.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/repository/FollowRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowService.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/repository/FollowRepositoryTest.java
=> [BE] 팔로워 조회 API 작성

BE/src/main/java/com/newsainturtle/shadowmate/follow/enums/FollowStatus.java, BE/src/main/java/com/newsainturtle/shadowmate/user/constant/UserConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/user/controller/UserController.java, BE/src/main/java/com/newsainturtle/shadowmate/user/dto/UserResponse.java, BE/src/main/java/com/newsainturtle/shadowmate/user/exception/UserErrorResult.java, BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserService.java, BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/auth/UserRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserServiceTest.java
=> [BE] 회원검색 API 작성

BE/src/main/java/com/newsainturtle/shadowmate/follow/constant/FollowConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/controller/FollowController.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/dto/DeleteFollowerRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/exception/FollowErrorResult.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/repository/FollowRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowService.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/repository/FollowRepositoryTest.java
=> [BE] 팔로워 삭제 API 작성

BE/src/main/java/com/newsainturtle/shadowmate/planner/constant/PlannerConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/controller/PlannerController.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/response/CalendarDayResponse.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/response/SearchCalendarResponse.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/TodoRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerService.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/DailyPlannerServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/PlannerControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/TodoRepositoryTest.java
=> [BE] 캘린더 조회 API 작성

FE/src/components/mypage/MyPageTab.tsx
close #164 
- 마이페이지 탭 input 태그 에러 수정
=> [FE] 마이페이지 탭 input 태그 에러 수정

FE/src/components/mypage/details/friend/Follower.tsx, FE/src/components/mypage/details/friend/Following.tsx, FE/src/components/mypage/details/friend/MyFriend.tsx, FE/src/components/mypage/details/friend/Search.tsx, FE/src/pages/MyPage.tsx, FE/src/styles/mypage/MyPage.module.scss, FE/src/util/data/FriendData.ts, FE/src/util/friend.interface.ts
close #163 
- 마이페이지 친구 데이터 타입 구분 기능 추가
- 마이페이지 친구 스크롤 위치 변경
- 마이페이지 친구 검색 입력 state 추가
=> [FE] 마이페이지 친구 데이터 타입 구분 기능 추가 

BE/src/main/java/com/newsainturtle/shadowmate/follow/constant/FollowConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/controller/FollowController.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/dto/DeleteFollowingRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowService.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/repository/FollowRepositoryTest.java
=> [BE] 팔로잉 삭제 API 작성

BE/src/main/java/com/newsainturtle/shadowmate/follow/constant/FollowConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/controller/FollowController.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/dto/ReceiveFollowRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/exception/FollowErrorResult.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowService.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/repository/FollowRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/repository/FollowRequestRepositoryTest.java
=> [BE] 친구신청 수락/거절 API 작성

BE/build.gradle, BE/src/main/java/com/newsainturtle/shadowmate/auth/entity/EmailAuthentication.java, BE/src/main/java/com/newsainturtle/shadowmate/auth/service/AuthServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/auth/service/RedisService.java, BE/src/main/java/com/newsainturtle/shadowmate/auth/service/RedisServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/config/RedisConfig.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/auth/AuthServiceTest.java
close #171
- 이메일 인증 API 작성
- 레디스 설정
=> [BE] 이메일 인증 API 작성

BE/src/main/java/com/newsainturtle/shadowmate/follow/constant/FollowConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/controller/FollowController.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/dto/FollowRequestResponse.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/repository/FollowRequestRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowService.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/user/dto/UserResponse.java, BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/repository/FollowRequestRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserControllerTest.java
=> [BE] 받은 친구신청 목록 조회 API 작성

BE/Dockerfile, BE/src/main/java/com/newsainturtle/shadowmate/user/entity/User.java
=> [BE] Dockerfile 생성

FE/config/webpack.prod.js
close #
- 웹팩 외부 도메인 접속 허용 설정 추가
=> [FE] 웹팩 외부 도메인 접속 허용 설정

BE/src/main/java/com/newsainturtle/shadowmate/auth/constant/AuthConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/auth/controller/AuthController.java, BE/src/main/java/com/newsainturtle/shadowmate/auth/dto/CheckEmailAuthenticationCodeRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/auth/dto/SendEmailAuthenticationCodeRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/auth/exception/AuthErrorResult.java, BE/src/main/java/com/newsainturtle/shadowmate/auth/service/AuthService.java, BE/src/main/java/com/newsainturtle/shadowmate/auth/service/AuthServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/auth/AuthControlloerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/auth/AuthServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/auth/AuthControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/auth/AuthServiceTest.java
close #175
- 이메일 인증 응답 API 작성
- 이메일 인증관련 클래스 및 메소드명 수정
=> [BE] 이메일 인증 응답 API 작성

BE/src/main/java/com/newsainturtle/shadowmate/config/MailConfig.java, BE/src/main/java/com/newsainturtle/shadowmate/user/entity/User.java
=> [BE] MailConfig 생성

FE/config/webpack.prod.js, FE/package-lock.json, FE/package.json
close #
- TypeScript 버전 다운그레이드 변경 (-> v 5.0.4)
=> [FE] TypeScript 버전 다운그레이드 변경 (-> v 5.0.4)

BE/build.gradle
=> [BE] SonarQube 적용

FE/package-lock.json, FE/package.json
close #
- TypeScript 버전 변경 (-> v 4.9.5)
=> [FE] TypeScript 버전 변경 (-> v 4.9.5)

FE/package-lock.json, FE/package.json
close #
- typescript 버전 업그레이드 (-> v 5.1.6)
=> [FE] TypeScript 버전 업그레이드 변경 (-> v 5.1.6)

BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/request/AddTimeTableRequest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/auth/AuthControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/auth/AuthServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/auth/UserRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/DailyPlannerServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/PlannerControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/WeeklyPlannerServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/DailyPlannerLikeRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/DailyPlannerRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/TimeTableRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/TodoRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/UserRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/WeeklyRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/WeeklyTodoRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/CategoryColorRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/CategoryRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/DdayRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/TodoRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/UserRepositoryTest.java
#192
- 코드 악취가 굉장히 많네요,,🥲 500개,, 조금조금 수정해보겠습니다.
- public 접근제한자 지우기
- 정규식 간결화: `[0-9]`처럼 모든 숫자를 사용할때는 `\\d`를 사용하는 것으로 간결하게 표현할 수 있다고 합니다!
=> [BE] 소나큐브 코드 악취 수정

BE/build.gradle, BE/gradle/wrapper/gradle-wrapper.properties
=> [BE] Sonarqube 버전 수정

BE/src/main/java/com/newsainturtle/shadowmate/config/CorsConfig.java
=> [BE] cors에러 수정

BE/src/main/java/com/newsainturtle/shadowmate/auth/controller/AuthController.java, BE/src/main/java/com/newsainturtle/shadowmate/config/auth/PrincipalDetails.java, BE/src/main/java/com/newsainturtle/shadowmate/config/jwt/JwtAuthenticationFilter.java, BE/src/main/java/com/newsainturtle/shadowmate/config/jwt/JwtAuthorizationFilter.java
=> [BE] 로그인 응답 API 작성

BE/src/main/java/com/newsainturtle/shadowmate/planner/exception/PlannerErrorResult.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/WeeklyPlannerServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/PlannerControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/WeeklyPlannerServiceTest.java
close #211
- `getOrCreateWeeklyPlanner`사용으로 인해 `@Transactional` 어노테이션이 필요했지만, 
- `getWeeklyPlanner` 메소드를 작성해 사용함으로써 문제 해결
=> [BE] 주간 플래너 조회 메소드 생성

FE/src/api/Api.ts, FE/src/api/BaseUrl.ts
close #212
- BaseUrl 및 Axios 메서드 설정
=> [FE] BaseUrl 및 Axios 메서드 설정

BE/src/main/java/com/newsainturtle/shadowmate/auth/exception/AuthErrorResult.java, BE/src/main/java/com/newsainturtle/shadowmate/auth/service/AuthServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/auth/service/RedisService.java, BE/src/main/java/com/newsainturtle/shadowmate/auth/service/RedisServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/user/repository/UserRepository.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/auth/AuthControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/auth/AuthServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/auth/UserRepositoryTest.java
close #205
- 일반 계정 사용자 조회 레포지토리 메소드 작성
- 회원가입 서비스 코드 수정
=> [BE] 이메일 인증 로직 수정

BE/src/test/java/com/newsainturtle/shadowmate/yn/auth/AuthControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/auth/AuthServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/auth/UserRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/DailyPlannerServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/PlannerControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/WeeklyPlannerServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/DailyPlannerLikeRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/DailyPlannerRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/TimeTableRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/TodoRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/UserRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/WeeklyRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/WeeklyTodoRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/CategoryRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/DdayRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/TodoRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/UserRepositoryTest.java
close #219
- 테스트코드 리팩토링
- 🚨 실제 사용자가 계정을 등록하여 레포지토리 테스트 코드가 실패가 뜸!
- 테스트 코드에서 사용하는 계정은 다른 사람들이 등록하지 않을 법한 계정으로 변경
- 유효하지 않은 필드 값 실패 케이스 파라미터화 시켜 하나로 합침
=> [BE] 테스트코드 리팩토링

BE/src/main/java/com/newsainturtle/shadowmate/config/MailConfig.java, BE/src/main/java/com/newsainturtle/shadowmate/config/jwt/JwtAuthorizationFilter.java
=> [BE] 구글 계정에서 네이버 계정으로 변경

BE/src/main/java/com/newsainturtle/shadowmate/config/auth/PrincipalDetails.java, BE/src/main/java/com/newsainturtle/shadowmate/config/auth/PrincipalDetailsService.java, BE/src/main/java/com/newsainturtle/shadowmate/config/jwt/JwtAuthenticationFilter.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/auth/AuthServiceTest.java
=> [BE] 로그인 유저ID 값 응답 수정

BE/src/main/java/com/newsainturtle/shadowmate/auth/service/AuthServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/user/repository/UserRepository.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/auth/AuthServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/auth/UserRepositoryTest.java
close #223
- 중복이메일 확인 시 탈퇴여부를 확인했는데, 필요없는 로직이라 생각하여 수정함
=> [BE] 중복이메일 확인 레포지토리 메소드 수정

BE/src/main/java/com/newsainturtle/shadowmate/auth/controller/AuthController.java, BE/src/main/java/com/newsainturtle/shadowmate/config/oauth/OAuth2LoginSuccessHandler.java
=> [BE] 구글 로그인 API 수정

BE/src/main/java/com/newsainturtle/shadowmate/config/CorsConfig.java
=> [BE] corsconfig 수정

BE/src/main/java/com/newsainturtle/shadowmate/config/auth/PrincipalDetails.java, BE/src/main/java/com/newsainturtle/shadowmate/config/auth/PrincipalDetailsService.java, BE/src/main/java/com/newsainturtle/shadowmate/config/jwt/JwtAuthenticationFilter.java
=> [BE] 로그인시 email 수정

BE/src/main/java/com/newsainturtle/shadowmate/config/RedisConfig.java
=> [BE] RedisConfig 수정

BE/src/main/java/com/newsainturtle/shadowmate/config/oauth/OAuth2LoginSuccessHandler.java, BE/src/main/java/com/newsainturtle/shadowmate/config/oauth/PrincipalOauth2UserService.java
=> [BE] 구글 로그인 ID 반환 수정

BE/src/main/java/com/newsainturtle/shadowmate/config/oauth/OAuth2LoginSuccessHandler.java
=> [BE] 구글 로그인 API 주소 수정

BE/src/main/java/com/newsainturtle/shadowmate/follow/repository/FollowRequestRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/FollowRequestRepositoryTest.java
#135 
- 친구공개/비공개 -> 공개 설정시 팔로우 신청 목록에 있는 사람들 모두 내 팔로워 목록에 추가
=> [BE] 플래너 공개 여부 설정 로직 수정

FE/config/webpack.config.js
=> [FE] 웹팩 svg 설정 수정

FE/src/api/MultipartAxios.ts, FE/src/components/auth/login/Login.tsx, FE/src/store/authSlice.ts
close #57 
- 구글 로그인 후 쿠키 삭제
- sessionStorage에 token 저장하는 로직 수정
- 로그아웃 시 localStorage에 저장한 token, id 삭제
=> [FE] 구글 로그인 후 쿠키 삭제

FE/src/api/Api.ts, FE/src/api/BaseUrl.ts, FE/src/components/planner/week/Week.tsx, FE/src/components/planner/week/todo/WeekTodoInput.tsx, FE/src/components/planner/week/todo/WeekTodoItem.tsx, FE/src/store/authSlice.ts
close #260 
- BaseURL userId 타입 변경 -> 기존 userId 값 변경
- authSlice userId 분리 -> 기존 selector 변경
=> [FE] BaseURL 수정 및 userId 분리

BE/src/main/java/com/newsainturtle/shadowmate/social/entity/Social.java
=> [BE] Social Entity 추가

BE/src/main/java/com/newsainturtle/shadowmate/planner/constant/PlannerConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/controller/PlannerController.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/request/ShareSocialRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerService.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/social/repository/SocialRepository.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/DailyPlannerServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/PlannerControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/SocialRepositoryTest.java
=> [BE] 소셜 공유 API 작성

FE/Dockerfile
=> [FE] dockerfile 수정

FE/src/components/mypage/MyPageDetail.tsx, FE/src/components/mypage/MyPageFrame.tsx, FE/src/components/mypage/details/diary/Category.tsx, FE/src/components/mypage/item/CategoryColorItem.tsx, FE/src/components/mypage/item/CategoryColorList.tsx, FE/src/components/mypage/item/MyPageCategoryItem.tsx, FE/src/components/mypage/list/CategoryList.tsx, FE/src/hooks/configStore.ts, FE/src/pages/MyPage.tsx, FE/src/store/mypageSlice.ts, FE/src/styles/mypage/MyPage.module.scss, FE/src/util/planner.interface.ts
close #262 
- 마이페이지 redux slice 생성 (mypageSlice.ts)
- 카테고리 조회, 생성, 수정, 삭제 API 연결
- 카테고리 관련 컴포넌트 redux state 사용하도록 수정
- 카테고리명 2~10자만 수정 가능, 아닐 시 input error문 출력, 그 외 helperText로 글자수 출력.
- 카테고리 없을 때 발생하던 에러 수정
=> [FE] 마이페이지 카테고리 설정 API 연결

FE/src/api/Api.ts, FE/src/components/planner/month/Month.tsx, FE/src/components/planner/month/MonthCalendar.tsx, FE/src/hooks/configStore.ts, FE/src/store/planner/monthSlice.ts
close #274 
- 캘린더 조회 API 연결
- 캘린더 slice 생성 (monthSlice.ts)
=> [FE] 월별 플래너 조회 API 연결 

BE/src/main/java/com/newsainturtle/shadowmate/planner/service/SearchPlannerServiceImpl.java
close #279
- 캘린더 접근 권한 확인 에러 수정
=> [BE] 캘린더 접근 권한 확인 에러 수정

FE/src/components/planner/day/todo/TodoItem.tsx, FE/src/components/planner/day/todo/TodoList.tsx
=> [FE] 카테고리 ID 에러 수정

FE/src/components/mypage/details/diary/Diary.tsx, FE/src/components/planner/month/Month.tsx, FE/src/store/planner/monthSlice.ts
close #278 
- 마이페이지 다이어리 공개 여부 설정 API 연결
- 프로필 조회 API 연결 후, "plannerAccessScope" state 경로 변경 예정 (monthSlice -> authSlice)
=> [FE] 마이페이지 다이어리 공개 여부 설정 API 연결

BE/src/main/java/com/newsainturtle/shadowmate/user/constant/UserConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/user/controller/UserController.java, BE/src/main/java/com/newsainturtle/shadowmate/user/dto/UpdateUserRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/user/repository/UserRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserService.java, BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserServiceTest.java
=> [BE] 내 정보 설정 API 작성

BE/src/main/java/com/newsainturtle/shadowmate/user/constant/UserConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/user/controller/UserController.java, BE/src/main/java/com/newsainturtle/shadowmate/user/dto/UpdatePasswordRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/user/exception/UserErrorResult.java, BE/src/main/java/com/newsainturtle/shadowmate/user/repository/UserRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserService.java, BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserServiceTest.java
=> [BE] 비밀번호 수정 API 작성

FE/src/components/common/CategorySelector/index.tsx, FE/src/components/planner/week/Week.tsx, FE/src/components/planner/week/list/WeekItem.tsx, FE/src/components/planner/week/list/WeekItemInput.tsx, FE/src/components/planner/week/list/WeekList.tsx, FE/src/pages/MyPage.tsx, FE/src/pages/Planner/MonthPage.tsx, FE/src/store/planner/weekSlice.ts
close #286 
- 주별 플래너에서 일일 할일 조회, 등록, 수정, 삭제 API 연결
- 주별 플래너 일일 회고 수정 API 연결
- 주별 플래너 데이터, 카테고리 선택 모달에서 카테고리 목록 데이터를 redux state값으로 변경
- weekSlice 일부 수정 (변수명, action, selector 추가)
=> [FE] 주별 플래너 API 연결

BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowServiceImpl.java
=> [BE] 팔로우 신청 응답 API 수정

BE/build.gradle, BE/lombok.config, BE/src/main/java/com/newsainturtle/shadowmate/auth/dto/SendEmailAuthenticationCodeRequest.java
close #28
- `./gradlew --console verbose test jacocoTestReport jacocoTestCoverageVerification`를 통해 jacoco를 실행했습니다
=> [BE] Jacoco 설정

BE/src/main/java/com/newsainturtle/shadowmate/social/constant/SocialConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/social/controller/SocialController.java, BE/src/main/java/com/newsainturtle/shadowmate/social/exception/SocialErrorResult.java, BE/src/main/java/com/newsainturtle/shadowmate/social/service/SocialService.java, BE/src/main/java/com/newsainturtle/shadowmate/social/service/SocialServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/social/SocialControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/social/SocialRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/social/SocialServiceTest.java
=> [BE] 공유 플래너 삭제 API 작성

BE/src/main/java/com/newsainturtle/shadowmate/auth/service/AuthServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/auth/service/RedisService.java, BE/src/main/java/com/newsainturtle/shadowmate/auth/service/RedisServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/auth/AuthServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserServiceTest.java
=> [BE] 닉네임 중복검사 API 작성

FE/public/index.html, FE/src/App.tsx, FE/src/components/common/Alert/index.tsx, FE/src/components/common/Loading/index.tsx, FE/src/components/common/Modal/index.tsx, FE/src/components/mypage/details/diary/Diary.tsx, FE/src/components/planner/day/todo/TodoItem.tsx, FE/src/components/planner/week/list/WeekItem.tsx, FE/src/pages/commonPage.tsx, FE/src/styles/common/Alert.module.scss, FE/src/styles/common/Loading.module.scss, FE/src/styles/common/Modal.module.scss, FE/src/styles/mypage/MyPage.module.scss
close #294 
- 공통 모달 컴포넌트 수정 (버튼 개수로 디자인 구분)
- noBtn: 버튼 없음
- oneBtn: 버튼 하나 있음, click 동작만 수행
- twoBtn: 버튼 두개 있음, 하나는 취소, 하나는 click 동작 수행
- 공통 Alert, 로딩 컴포넌트 생성 (commonPage에서 확인 가능)
=> [FE] 공통 모달 컴포넌트 수정 및 alert, 로딩 컴포넌트 생성

FE/config/webpack.prod.js
close #
- webpack 빌드시 asset 크기 증량
=> [FE] 프론트엔드 빌드 에러 해결

BE/src/main/java/com/newsainturtle/shadowmate/auth/service/AuthServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/auth/service/RedisServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/social/repository/SocialRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/user/exception/UserErrorResult.java, BE/src/main/java/com/newsainturtle/shadowmate/user/repository/UserRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/auth/AuthServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/social/SocialRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserServiceTest.java
=> [BE] 닉네임 중복검증 API Redis 수정

BE/src/main/java/com/newsainturtle/shadowmate/follow/dto/FollowingResponse.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowServiceImpl.java
=> [BE] 팔로잉 조회 API 수정

BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/response/SearchDailyPlannerResponse.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/SearchPlannerServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/social/repository/SocialRepository.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/auth/AuthServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/SearchPlannerServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/SocialRepositoryTest.java
close #318
- 일일 플래너 조회 시 소셜 공유 여부 확인하기
=> [BE] 일일 플래너 조회 시 소셜 공유 여부 확인하기

BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserServiceTest.java
=> [BE] 회원 검색 빈값 수정

BE/src/main/java/com/newsainturtle/shadowmate/follow/dto/FollowerResponse.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowService.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserServiceTest.java
=> [BE] 팔로워 조회 API 응답 수정

BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserServiceImpl.java
=> [BE] 충돌 수정

FE/src/components/planner/month/MonthFriends.tsx, FE/src/styles/planner/Month.module.scss
close #313 
- 캘린더 팔로잉 목록 API 연결
=> [FE] 캘린더 팔로잉 목록 API 연결

FE/src/api/JsonAxios.ts
close #331 
- error status가 403일 때만 모달 오픈
=> [FE] 토큰 만료 모달 에러 수정

BE/src/main/java/com/newsainturtle/shadowmate/follow/repository/FollowRequestRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/exception/PlannerErrorResult.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/DailyPlannerServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/PlannerControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/FollowRequestRepositoryTest.java
close #335
- 일일플래너 소셜 공유시 플래너 공개범위 확인
- 플래너 범위 변경 시 나에게 온 친구요청 목록 삭제 코드 수정
=> [BE] 일일플래너 소셜 공유시 플래너 공개범위 확인

BE/src/main/java/com/newsainturtle/shadowmate/config/jwt/JwtAuthorizationFilter.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/auth/UserRepositoryTest.java
=> [BE] 닉네임 중복검사 API 수정

BE/src/main/java/com/newsainturtle/shadowmate/planner/controller/PlannerController.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/controller/PlannerSettingController.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/PlannerControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingControllerTest.java
=> [BE] 성공 상태코드 수정

BE/src/main/java/com/newsainturtle/shadowmate/auth/controller/AuthController.java, BE/src/main/java/com/newsainturtle/shadowmate/social/controller/SocialController.java, BE/src/main/java/com/newsainturtle/shadowmate/user/controller/UserController.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/auth/AuthControlloerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/social/SocialControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserControllerTest.java
=> [BE] 성공 상태 코드 수정

FE/src/api/Api.ts, FE/src/api/BaseUrl.ts, FE/src/components/planner/day/Header.tsx, FE/src/components/social/CardItem.tsx, FE/src/components/social/CardList.tsx, FE/src/components/social/SocialHeader.tsx, FE/src/pages/SocialPage.tsx, FE/src/store/friendSlice.ts, FE/src/styles/social/Social.module.scss
close #317 
- 소셜공유 API 연결
- 최신순, 인기순 조회 API 연결
- 닉네임 검색 조회 API 연결
- 공유된 내 플래너 삭제 API 연결
- 소셜 닉네임 검색 디바운싱
- 무한 스크롤 구현
- 페이지 로딩 상태 추가
- 디자인은 공통된 부분을 사용하기엔 어두워서 깜빡임이 더 부각됨. 때문에 임의로 투명하게 설정해둠
- 소셜 이미지와 프로필 클릭시 각각 월별, 일별 플래너 페이지로 이동(친구 플래너 열람 상태는 아님)
=> [FE] 소셜공유 API  연결

BE/src/main/java/com/newsainturtle/shadowmate/social/service/SocialServiceImpl.java
=> [BE] 공개된 플래너 최신순 정렬 수정

BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserServiceImpl.java
=> [BE] 비밀번호 변경 API 수정

BE/src/main/java/com/newsainturtle/shadowmate/auth/constant/AuthConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/auth/controller/AuthController.java, BE/src/main/java/com/newsainturtle/shadowmate/auth/service/AuthService.java, BE/src/main/java/com/newsainturtle/shadowmate/auth/service/AuthServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/social/service/SocialServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/user/constant/UserConstant.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/auth/AuthControlloerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/auth/AuthServiceTest.java
=> [BE] 닉네임 중복검사 삭제 API 작성

FE/src/App.tsx, FE/src/components/auth/AuthHeader.tsx, FE/src/components/common/Header/Toggle.tsx, FE/src/components/common/Profile/index.tsx, FE/src/components/mypage/details/myInfo/CancelMembership.tsx, FE/src/store/authSlice.ts, FE/src/styles/auth/Landing.module.scss, FE/src/styles/common/Profile.module.scss
close #353 
- 로그아웃 기능 추가
- 사용자 테마 로컬스토리지 저장
- 로컬스토리지에 저장된 테마가 없을 경우, 브라우저 테마로 기본 적용
=> [FE] 로그아웃 및 사용자 테마 저장

FE/src/components/auth/login/Login.tsx
close #365 
- 구글 로그인 에러 수정
로컬 확인 시 OAuth2LoginSuccessHandler.java > handle() > `String targetURL = http://localhost:3000/login`으로 변경
=> [FE] 구글 로그인 에러 수정

FE/package.json
=> [FE] 프론트 빌드 설정 변경

FE/src/App.tsx, FE/src/api/JsonAxios.ts, FE/src/components/common/Alert/index.tsx, FE/src/components/planner/month/MonthCalendar.tsx, FE/src/components/planner/week/Week.tsx, FE/src/hooks/configStore.ts, FE/src/pages/Planner/DayPage.tsx, FE/src/pages/commonPage.tsx, FE/src/store/alertSlice.ts, FE/src/styles/common/Loading.module.scss
close #328 
- alertSlice.ts 추가
- axios interceptor 에서 response status가 202일 시, alert 출력
- 공통 로딩 컴포넌트 배경색 제거
- 캘린더, 주별 플래너 로딩 동작 추가 (나머지는 필요없을 것 같아서, 나중에 QA 시 필요하다는 판단 들면 추가하는 게 좋을 듯)
(소셜은 develop pull 받고 따로 이슈 파서 진행하도록 할게욤)
=> [FE] 로딩 및 알림(Alert) 추가

FE/src/components/planner/day/Header.tsx, FE/src/components/planner/day/Ment.tsx, FE/src/components/planner/day/todo/TimeTable.tsx, FE/src/components/planner/day/todo/TodoList.tsx, FE/src/pages/Planner/DayPage.tsx, FE/src/store/planner/daySlice.ts, FE/src/styles/planner/day.module.scss
close #349 
- 일별 플래너 좋아요 추가 및 삭제 API 연결
- 일별 플래너 모든 컴포넌트 배경색 적용
- 소셜 공유 캡쳐 때 기본 흰색으로 나와서 배경색을 라이트/다크 모드에 맞게 변경함
=> [FE] 일별 플래너 친구 좋아요 추가/취소 API 연결

FE/src/components/planner/week/Week.tsx, FE/src/components/planner/week/list/WeekItem.tsx, FE/src/components/planner/week/list/WeekList.tsx, FE/src/components/planner/week/todo/WeekTodo.tsx, FE/src/styles/common/Profile.module.scss, FE/src/styles/planner/Week.module.scss
close #359 
- 친구 주별 플래너 수정 막기
- 친구 플래너 -> 친구 프로필 -> 친구추가 버튼 배경색 변경
=> [FE] 친구 주별 플래너 수정 막기

FE/src/components/social/CardItem.tsx, FE/src/components/social/CardList.tsx, FE/src/pages/SocialPage.tsx, FE/src/styles/social/Social.module.scss
close #371
- 소셜 첫 렌더링 데이터 2배로 가져오기
- 소셜 정렬/검색 변경시 스크롤 맨 위로 이동
- 소셜 이미지 스켈레톤 UI 적용
=> [FE] 소셜 페이지 이미지 로딩 

FE/package.json, FE/src/hooks/configStore.ts
close #374 
- redux-persist 암호화 라이브러리 설치 및 설정 추가
1. `.env` 파일 수정 (노션 참고)
2. `npm i` 실행
=> [FE] redux-persist 암호화 라이브러리 설치 및 설정 추가

BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/response/CalendarDayTotalResponse.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/response/SearchCalendarResponse.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/SearchPlannerServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/SearchPlannerServiceTest.java
close #390
- 캘린더 조회 API에 월별 통계 추가
=> [BE] 캘린더 조회 API에 월별 통계 추가

BE/src/main/java/com/newsainturtle/shadowmate/planner/constant/PlannerConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/controller/PlannerController.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/request/AddVisitorBookRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/response/AddVisitorBookResponse.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/VisitorBook.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/exception/PlannerErrorResult.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/VisitorBookRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/MonthlyPlannerService.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/MonthlyPlannerServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/auth/AuthControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/MonthlyPlannerServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/PlannerControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/VisitorBookRepositoryTest.java
close #381
- 방명록 엔티티 추가
- 방명록 추가 API
=> [BE] 방명록 추가 API 작성

BE/src/main/java/com/newsainturtle/shadowmate/planner/constant/PlannerConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/controller/PlannerController.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/request/RemoveVisitorBookRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/exception/PlannerErrorResult.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/VisitorBookRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/MonthlyPlannerService.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/MonthlyPlannerServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/MonthlyPlannerServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/PlannerControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/VisitorBookRepositoryTest.java
=> [BE] 방명록 삭제 API 작성

BE/src/main/java/com/newsainturtle/shadowmate/user/constant/UserConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/user/controller/UserController.java, BE/src/main/java/com/newsainturtle/shadowmate/user/dto/UpdateIntroductionRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/user/entity/User.java, BE/src/main/java/com/newsainturtle/shadowmate/user/repository/UserRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserService.java, BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserServiceTest.java
=> [BE] 소개글 작성 API 추가

FE/src/components/auth/AuthHeader.tsx
close #388
- auth페이지 헤더 토글 버튼 제거
=> [FE] auth페이지 헤더 변경

FE/src/App.scss, FE/src/components/common/FriendProfile/index.tsx, FE/src/components/common/FriendProfileIcon/index.tsx, FE/src/components/common/Profile/index.tsx, FE/src/components/planner/month/Month.tsx, FE/src/components/planner/month/MonthDetail.tsx, FE/src/components/planner/month/MonthDetailInfo/GuestBook.tsx, FE/src/components/planner/month/MonthDetailInfo/Introduction.tsx, FE/src/components/planner/month/MonthDetailInfo/Statistics.tsx, FE/src/components/planner/month/MonthFriends.tsx, FE/src/components/planner/month/MonthIconBox.tsx, FE/src/styles/common/Profile.module.scss, FE/src/styles/planner/Month.module.scss, FE/src/util/data/GuestBookData.ts
close #382 
- 캘린더 컴포넌트 생성 및 배치
- ‼️ 페이지 이동하는 버튼은 미연결 상태 (친구검색 버튼, 마이페이지 수정 버튼) ‼️ 
- ‼️ 반응형 미고려 상태 ‼️  -> 배치 혹은 폰트 크기를 변경해줘야 할듯
=> [FE] 캘린더 컴포넌트 생성 및 배치

BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/response/CalendarDayTotalResponse.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/response/SearchCalendarResponse.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/DailyPlannerLikeRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/SearchPlannerServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/SearchPlannerServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/DailyPlannerLikeRepositoryTest.java
close #398
- 캘린더 조회 API에 좋아요 월별 카운트 기능 추가
=> [BE] 캘린더 조회 API에 좋아요 월별 카운트 기능 추가

BE/src/main/java/com/newsainturtle/shadowmate/config/SecurityConfig.java
=> [BE] 구글로그인 주소 수정

BE/src/main/java/com/newsainturtle/shadowmate/follow/constant/FollowConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/controller/FollowController.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/dto/CountFollowResponse.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/repository/FollowRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowService.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/repository/FollowRepositoryTest.java
=> [BE] 팔로우 팔로잉 카운트 API 작성

FE/src/components/common/FriendProfile/index.tsx, FE/src/components/mypage/details/friend/MyFriendFrame.tsx
close #401 
- 팔로워 목록에서 친구 아닌 사용자 버튼  `친구 신청` → `친구 신청/취소` 버튼으로 수정
- 친구 팔로우 상태 변경시 버튼 변경
- 친구 프로필 상태 변경 state 삭제
=> [FE] 팔로우 친구 신청 수정

BE/src/main/java/com/newsainturtle/shadowmate/user/controller/UserController.java
=> [BE] API업데이트 리팩토링

BE/src/main/java/com/newsainturtle/shadowmate/common/entity/CommonEntity.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/entity/Category.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/entity/Dday.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/user/entity/User.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingServiceTest.java
#412
- 플래너 설정 부분 데이터 업데이트 코드 리팩토링
=> [BE] 플래너 설정 부분 데이터 업데이트 코드 리팩토링

BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowServiceImpl.java
=> [BE] 코드 리팩토링

BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/DailyPlanner.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/Todo.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/social/entity/Social.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/DailyPlannerServiceTest.java
#412
- 일일 플래너 부분 데이터 업데이트 코드 리팩토링
=> [BE] 일일 플래너 부분 데이터 업데이트 코드 리팩토링

BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserControllerTest.java
=> [BE] 비밀번호 Test코드 수정

BE/src/main/java/com/newsainturtle/shadowmate/config/auth/PrincipalDetailsService.java, BE/src/main/java/com/newsainturtle/shadowmate/user/repository/UserRepository.java
=> [BE] 탈퇴회원 로그인 코드 리팩토링

BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/WeeklyTodo.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/WeeklyPlannerServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/WeeklyPlannerServiceTest.java
#412
- 주간 플래너 부분 데이터 업데이트 코드 리팩토링
=> [BE] 주간 플래너 부분 데이터 업데이트 코드 리팩토링

BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/user/entity/User.java, BE/src/main/java/com/newsainturtle/shadowmate/user/repository/UserRepository.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingServiceTest.java
close #412
- set메서드에서 update 쿼리문 사용으로 변경!
=> [BE] 플래너 공개 여부 설정 코드 리팩토링

BE/src/main/java/com/newsainturtle/shadowmate/user/repository/UserRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserServiceTest.java
=> [BE] 유저 탈퇴 API 리팩토링

BE/src/main/java/com/newsainturtle/shadowmate/user/dto/ProfileResponse.java, BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserServiceImpl.java
=> [BE] PlannerAccessScope 타입 변경

FE/src/components/planner/week/list/WeekList.tsx
close #403 
- 주별 플래너 작성 시 이전 내용 없어지는 에러 수정
=> [FE] 주별 플래너 작성 시 이전 내용 없어지는 에러 수정

FE/src/components/planner/month/Month.tsx
close #407 
- plannerAccessScope "PRIVATE" -> "비공개" 변경
=> [FE] 다이어리 공개 여부 API 수정 반영

FE/src/components/planner/month/Month.tsx
close #435 
- 캘린더 비공개 설정 시 나한테도 비공개 되는 에러 수정 ... ^^ㅜ..
=> [FE] 캘린더 비공개 에러 수정

BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/VisitorBookRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/MonthlyPlannerServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/MonthlyPlannerServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/VisitorBookRepositoryTest.java
close #434
- 방문자 닉네임과 프로필 사진 가져오기 수정
- 방명록 5개 전달에서 10개 전달로 수정
=> [BE] 방명록 에러 수정

BE/src/main/java/com/newsainturtle/shadowmate/user/constant/UserConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/user/controller/UserController.java, BE/src/main/java/com/newsainturtle/shadowmate/user/dto/SearchIntroductionResponse.java, BE/src/main/java/com/newsainturtle/shadowmate/user/repository/UserRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserService.java, BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserServiceTest.java
=> [BE] 소개글 조회 API 작성

BE/src/main/java/com/newsainturtle/shadowmate/follow/controller/FollowController.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowService.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowServiceTest.java
=> [BE] 팔로우 팔로잉 개수 조회 유저검증 API 리팩토링

FE/src/components/planner/day/Ment.tsx, FE/src/components/planner/day/todo/TodoItem.tsx, FE/src/pages/Planner/DayPage.tsx, FE/src/styles/planner/day.module.scss
close #399
- 타임테이블 에러 잡기
- 일별 플래너 할일 상태 간격 반응형 style
- 카테고리 먼저 선택 막기
- 소셜 공유 캡쳐
- 가로 세로 비율 고정
- firebase 이미지 캡쳐 에러 해결(filebase cors에러 해결)
=> [FE] 일별 플래너 에러 수정 & 소셜공유

FE/src/components/planner/week/todo/WeekTodo.tsx, FE/src/components/planner/week/todo/WeekTodoInput.tsx, FE/src/components/planner/week/todo/WeekTodoItem.tsx, FE/src/styles/planner/Week.module.scss
close #440 
- 친구 주별 플래너 주차별 할 일 스크롤 안되는 에러 수정
- 주별 플래너 주차별 할 일 추가 시 다른 주차에 저장되는 에러 수정
=> [FE] 주별 플래너 에러 수정

FE/src/api/Api.ts, FE/src/util/regex.ts
close #452 
- 비밀번호 수정 API 메서드 Post → Put 으로 변경
- 상태메세지 모든 문자 허용
=> [FE] 비밀번호 변경 API 수정/상태메세지 모든 문자 허용

FE/src/components/common/Avatar/index.tsx
close #404 
- 공통 컴포넌트 Avatar property 에러 수정
=> [FE] 공통 컴포넌트 Avatar property 에러 수정

FE/src/components/social/SocialHeader.tsx
close #455 
- 소셜 닉네임 검색후 정렬 추가
=> [FE] 소셜 닉네임 검색후 정렬 추가

FE/src/api/JsonAxios.ts
=> [FE] 토큰 만료 에러 수정

BE/src/main/java/com/newsainturtle/shadowmate/follow/repository/FollowRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/repository/FollowRequestRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/user/controller/UserController.java, BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserService.java, BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/repository/FollowRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/repository/FollowRequestRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserServiceTest.java
=> [BE] 회원탈퇴시 팔로우삭제 API 리팩토링

BE/src/main/java/com/newsainturtle/shadowmate/social/service/SocialServiceImpl.java
=> [BE] 최신순 정렬 API 리팩토링

FE/src/components/mypage/MyPageFrame.tsx
=> [FE] 디데이 삭제 에러 수정

FE/src/App.tsx, FE/src/api/Api.ts, FE/src/api/BaseUrl.ts, FE/src/components/common/Profile/index.tsx, FE/src/components/mypage/MyPageTab.tsx, FE/src/components/planner/month/Month.tsx, FE/src/components/planner/month/MonthCalendar.tsx, FE/src/components/planner/month/MonthDetailInfo/GuestBook.tsx, FE/src/components/planner/month/MonthDetailInfo/Introduction.tsx, FE/src/components/planner/month/MonthDetailInfo/Statistics.tsx, FE/src/components/planner/month/MonthFriends.tsx, FE/src/components/planner/month/MonthIconBox.tsx, FE/src/components/social/CardList.tsx, FE/src/pages/MyPage.tsx, FE/src/store/planner/monthSlice.ts, FE/src/styles/planner/Month.module.scss, FE/src/util/data/GuestBookData.ts, FE/src/util/planner.interface.ts
close #433 
- 캘린더 소개글 조회/수정 API 연결
글자수 표시 및 100자 이상 작성 불가
- 캘린더 통계 중 팔로우 수 조회 연결
- 캘린더 방명록 조회/작성/삭제 API 연결
방명록 조회 시 무한스크롤 구현
방명록 작성 시 내 방명록 금지, 타인의 방명록에만 작성 가능
방명록 삭제 시 내 방명록에 있는 글, 그리고 타인의 방명록에 쓴 내 댓글 삭제 가능
NEW!
- 캘린더 친구 목록 스크롤 생성
마우스 드래그로 좌우 이동 (throttle 사용으로 버벅임 있음)
- 캘린더 버튼 연결 (친구 검색, 내 프로필 수정)
NEW!
- 방명록 input width 최대 수정
- 캘린더 아이콘 크기, padding 수정 + 방명록 높이 수정
- 방명록 삭제 버튼 공간 있도록 수정
NEW!
- 캘린더 오늘 날짜 표시
- 켈린더 할 일 있는 경우에만 숫자 표시
- 캘린더 날짜 이동 버튼 CSS 수정
=> [FE] 캘린더 API 연결

FE/src/components/auth/login/Login.tsx
close #473 
- 로그인 자동 로그인, 비밀번호 찾기 버튼 삭제
=> [FE] 로그인 자동 로그인, 비밀번호 찾기 버튼 삭제

FE/src/components/common/FriendProfile/index.tsx, FE/src/components/common/Modal/DeleteModal.tsx, FE/src/components/common/Modal/index.tsx, FE/src/components/mypage/MyPageDetail.tsx, FE/src/components/mypage/MyPageFrame.tsx, FE/src/components/mypage/details/myInfo/MyInfo.tsx, FE/src/components/planner/day/todo/TimeTable.tsx, FE/src/components/planner/day/todo/TodoItem.tsx, FE/src/components/planner/month/MonthDetailInfo/GuestBook.tsx, FE/src/components/planner/week/list/WeekItem.tsx, FE/src/components/planner/week/todo/WeekTodoItem.tsx, FE/src/components/social/CardItem.tsx, FE/src/components/social/CardList.tsx, FE/src/styles/common/Modal.module.scss
close #457 
- 캘린더
방명록 삭제 시 모달 확인
- 일별 플래너
할 일 삭제, 타임테이블 삭제 시 모달 확인
- 주별 플래너
할 일 삭제, 주차별 할 일 삭제 시 모달 확인
- 마이페이지 
프로필 사진 삭제 시 모달 확인
카테고리, 디데이 삭제 시 모달 확인
팔로우(팔로워, 팔로잉) 삭제 시 모달 확인 
NEW!
- 소셜 페이지
공유된 플래너 삭제 시 모달 확인
=> [FE] 공통 삭제 모달 생성 및 연결

FE/src/components/common/FriendProfile/index.tsx, FE/src/components/mypage/details/friend/MyFriendFrame.tsx
=> [FE] 팔로우 연속 삭제/플래너에서 친구 추가 에러 해결

FE/src/components/planner/week/list/WeekItemInput.tsx, FE/src/components/planner/week/todo/WeekTodoInput.tsx
close #485 
- 주별 플래너 주차별 할 일 생성 시 마우스가 blur되는 경우 저장
- 주별 플래너 할 일 생성 시 마우스가 blur되는 경우 저장
=> [FE] 주별 플래너 일정 생성 시 자동 저장 기능 추가

FE/src/App.tsx, FE/src/components/common/CategorySelector/index.tsx, FE/src/components/mypage/MyPageTab.tsx, FE/src/styles/mypage/MyPage.module.scss
close #487 
- 카테고리 선택창에 카테고리 추가 버튼 생성 및 페이지 연결
=> [FE] 카테고리 선택창에 카테고리 추가 버튼 생성 및 페이지 연결

FE/src/components/planner/month/MonthDetailInfo/Introduction.tsx, FE/src/components/planner/month/MonthIconBox.tsx, FE/src/styles/planner/Month.module.scss
close #489 
- 소개글 수정 시 글자색 변경 (gray-4 -> gray-5)
- 소개글 개행 반영, 글자수 카운터 저장 버튼 옆으로 옮김
=> [FE] 캘린더 소개글 수정 시 글자색 변경 및 개행 반영

FE/src/components/planner/month/Month.tsx
close #479 
- 캘린더 팔로우 수 출력 에러 수정 (코드 누락)
=> [FE] 캘린더 팔로우 수 에러 수정

BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowServiceTest.java
=> [BE] 팔로우 카운트 수 API 수정

BE/src/main/java/com/newsainturtle/shadowmate/ShadowmateApplication.java
=> [BE] 스프링부트 타임존 설정

FE/src/components/auth/signup/Signup.tsx, FE/src/components/mypage/details/myInfo/MyPassword.tsx
close #511
- 회원가입/비밀번호 변경 페이지에서 비밀번호 확인 입력하고 비밀번호 수정 입력시 값이 일치한지 검사 및 에러 표시
=> [FE] 비밀번호, 비밀번호 확인 일치 해결

FE/src/styles/social/Social.module.scss
close #496 
- 소셜페이지 item 높이 수정
=> [FE] 소셜페이지 높이 수정

BE/src/main/java/com/newsainturtle/shadowmate/common/DateCommonService.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/DailyPlanner.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/Weekly.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/DailyPlannerRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/WeeklyRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/MonthlyPlannerServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/SearchPlannerServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/WeeklyPlannerServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/entity/Dday.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/repository/DdayRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/social/dto/SearchSocialResponse.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/social/SocialControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/social/SocialRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/social/SocialServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/DailyPlannerServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/SearchPlannerServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/WeeklyPlannerServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/DailyPlannerLikeRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/DailyPlannerRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/SocialRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/TimeTableRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/TodoRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/WeeklyRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/WeeklyTodoRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/DdayRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/SocialRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/TodoRepositoryTest.java
close #519
- Date타입에서 LocalDate타입으로 변경
=> [BE] Date타입에서 LocalDate타입으로 변경

FE/src/components/common/FriendProfileIcon/index.tsx, FE/src/components/common/Profile/index.tsx, FE/src/components/planner/month/MonthFriends.tsx, FE/src/pages/Planner/MonthPage.tsx, FE/src/store/friendSlice.ts, FE/src/styles/common/Profile.module.scss
close #491 
- 팔로우 리스트 friendSlice에 state 생성
- 캘린더 프로필 팔로잉 신청 버튼 생성 및 API 연결
=> [FE] 캘린더 프로필 팔로잉 신청 버튼 생성 및 API 연결

FE/src/styles/planner/Month.module.scss
close #504 
- 캘린더 소개글 우측 여백 추가
- 캘린더 소개글 높이 수정
=> [FE] 캘린더 소개글 여백 추가 및 높이 수정

BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/DailyPlanner.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/Weekly.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/DailyPlannerRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/WeeklyRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/SearchPlannerServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/WeeklyPlannerServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/entity/Dday.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/repository/DdayRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/social/dto/SearchSocialResponse.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/social/SocialControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/social/SocialRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/social/SocialServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/DailyPlannerServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/SearchPlannerServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/WeeklyPlannerServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/DailyPlannerLikeRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/DailyPlannerRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/SocialRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/TimeTableRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/TodoRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/WeeklyRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/WeeklyTodoRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/DdayRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/SocialRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/TodoRepositoryTest.java
close #524
- 엔티티 LocalDate타입에서 String타입으로 변경
=> [BE] 엔티티 LocalDate타입에서 String타입으로 변경

FE/src/components/mypage/details/myInfo/MyInfo.tsx
close #529 
- 마이페이지 프로필 삭제 시 모달 닫는 함수 추가
=> [FE] 마이페이지 프로필 삭제 시 모달 에러 수정

BE/src/main/java/com/newsainturtle/shadowmate/auth/service/RedisServiceImpl.java
=> [BE] 회원가입 후 레디스에서 이메일 인증 데이터 삭제

BE/src/main/java/com/newsainturtle/shadowmate/config/oauth/PrincipalOauth2UserService.java, BE/src/main/java/com/newsainturtle/shadowmate/user/entity/User.java
=> [BE] 소셜회원가입, 일반 가입 리팩토링

BE/src/main/java/com/newsainturtle/shadowmate/auth/exception/AuthErrorResult.java, BE/src/main/java/com/newsainturtle/shadowmate/config/jwt/JwtAuthorizationFilter.java, BE/src/main/java/com/newsainturtle/shadowmate/config/jwt/JwtProvider.java, BE/src/main/java/com/newsainturtle/shadowmate/user/repository/UserRepository.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/auth/UserRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/repository/FollowRepositoryTest.java
=> [BE] 이메일 중복허용에 의한 findEmail 리팩토링

FE/src/components/auth/login/Login.tsx, FE/src/components/common/Header/index.tsx, FE/src/components/common/Popup/index.tsx, FE/src/components/planner/month/Month.tsx, FE/src/store/modalSlice.ts, FE/src/styles/common/Header.module.scss, FE/src/styles/common/Popup.module.scss
close #463 
- 헤더 설문으로 링크되는 컴포넌트 생성 및 배치
- 설문 팝업창 생성
- 로그인 이후 1번만 나타남
- '오늘 하루 보지 않기'를 누르면 재로그인 후에도 보이지 않음
- 모달 배경 클릭시 닫히지 않음
=> [FE] 사용자 서비스 설문 컴포넌트 생성

FE/src/components/common/Modal/DiaryConfirmModal.tsx, FE/src/components/common/Modal/TimeTableDeleteModal.tsx, FE/src/components/common/Modal/TokenExpiration.tsx, FE/src/components/mypage/details/diary/Diary.tsx, FE/src/components/planner/day/todo/TodoItem.tsx, FE/src/styles/common/Modal.module.scss
close #526 
- 일별 캘린더 타임테이블 삭제 경고 모달 생성 및 연결
- 다이어리 공개여부 경고 모달 컴포넌트 분리
- 모달 텍스트 색상 변경
=> [FE] 일별 캘린더 타임테이블 삭제 경고 모달 생성 및 연결

FE/src/components/mypage/MyPageFrame.tsx, FE/src/components/mypage/item/CategoryColorItem.tsx, FE/src/components/mypage/item/CategoryColorList.tsx, FE/src/styles/mypage/MyPage.module.scss
close #527 
- 카테고리 이모지 안내 문구 색상 연하게 변경
- 카테고리 색상 목록 데이터 및 인터페이스 변경 
- 카테고리 생성 시 카테고리 색상을 1번 인덱스 색상으로 설정
=> [FE] 카테고리 생성 시 기본 색상 설정 및 이모지 안내 문구 변경

FE/src/components/planner/week/list/WeekList.tsx, FE/src/styles/planner/Week.module.scss
close #537 
- 다른 사람의 주별 플래너에서 회고 입력 안내문 숨김 처리
=> [FE] 다른 사람의 주별 플래너에서 회고 입력 안내문 숨김 처리

FE/src/components/common/Popup/index.tsx, FE/src/components/planner/day/Header.tsx, FE/src/components/planner/day/Ment.tsx, FE/src/components/planner/month/Month.tsx, FE/src/index.scss, FE/src/pages/Planner/DayPage.tsx, FE/src/store/planner/daySlice.ts, FE/src/styles/planner/day.module.scss
close #543 
- 친구플래너일 때, 타임테이블 안내메세지 감추기
- 팝업 닫기 에러 해결
- 일별 플래너 하단 border 추가
- 일별 플래너 중간 border 위치 재조정
- 외부 스크롤 방지
- 형관펜 마우스 화면 크기 벗어나면 스크롤 생기는거 방지하기 위해 설정 추가 함
- 친구플래너인 경우, 
- 다짐/회고 글자수 감추기 및 이미지 없는 경우 칸 숨기기
- 할일 없을 때, 좋아요 버튼 비활성화
=> [FE] 일별 플래너 디데이 내용 표시 및 추가 디자인 설정

README.md
=> [공통] 화면 이미지 추가

FE/src/styles/planner/Month.module.scss
close #545 
- 캘린더 방명록 닉네임 마우스 호버 시 포인터로 변경
=> [FE] 캘린더 방명록 닉네임 마우스 상태 변경

FE/public/index.html
=> [FE] 메타데이터 추가

FE/public/index.html
=> [FE] 메타데이터 이미지 링크 변경

FE/public/index.html
=> [공통] 배포를 위한 main브랜치 머지

BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/request/AddTimeTableRequest.java
close #556
- 타임테이블 시작이나 종료시간이 00시 시간대에 있으면 유효성검사에 실패하는 오류가 있었습니다ㅜㅜ
- 정규식 수정해서 해결했습니다
=> [BE] 타임테이블 시간 유효성 검사 정규식 수정

BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/request/UpdateRetrospectionRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/request/UpdateTomorrowGoalRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/DailyPlanner.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/Todo.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/VisitorBook.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/WeeklyTodo.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/dto/request/AddCategoryRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/dto/request/AddDdayRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/dto/request/UpdateCategoryRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/dto/request/UpdateDdayRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/entity/Category.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/entity/Dday.java, BE/src/main/java/com/newsainturtle/shadowmate/user/entity/User.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/PlannerControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingControllerTest.java
close #563
- 디데이, 카테고리, 오늘의 회고, 내일의 다짐 등 제한 길이 수정
=> [BE] 플래너 글자 수 조정

FE/src/components/mypage/MyPageFrame.tsx
close #559 
- 카테고리, 디데이 저장 안되는 에러 수정 (글자수 범위 수정)
=> [FE] 카테고리, 디데이 저장 안되는 에러 수정

BE/build.gradle, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/social/constant/SocialConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/social/controller/SocialController.java, BE/src/main/java/com/newsainturtle/shadowmate/social/dto/SearchSocialPlannerResponse.java, BE/src/main/java/com/newsainturtle/shadowmate/social/entity/Social.java, BE/src/main/java/com/newsainturtle/shadowmate/social/exception/SocialErrorResult.java, BE/src/main/java/com/newsainturtle/shadowmate/social/repository/SocialRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/social/service/SocialService.java, BE/src/main/java/com/newsainturtle/shadowmate/social/service/SocialServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/social/SocialControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/social/SocialRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/social/SocialServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/DailyPlannerServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/SocialRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/SocialRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/social/SocialControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/social/SocialRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/social/SocialServiceTest.java
close #565
- 소셜 기간 필터 기능 추가
- 소셜 조회 관련 로직 리팩토링
=> [BE] 소셜 기간 필터 설정 및 소셜 조회 API 합치기

FE/src/components/auth/login/Login.tsx, FE/src/components/common/Avatar/index.tsx, FE/src/components/common/CategorySelector/index.tsx, FE/src/components/common/Dday/index.tsx, FE/src/components/common/Header/Menu.tsx, FE/src/components/common/Modal/TokenExpiration.tsx, FE/src/components/mypage/MyPageFrame.tsx, FE/src/components/mypage/MyPageTab.tsx, FE/src/components/mypage/details/diary/Category.tsx, FE/src/components/mypage/details/diary/Dday.tsx, FE/src/components/mypage/details/friend/MyFriend.tsx, FE/src/components/mypage/item/CategoryColorList.tsx, FE/src/components/mypage/item/MyPageDdayItem.tsx, FE/src/components/mypage/list/DdayList.tsx, FE/src/components/planner/month/MonthCalendar.tsx, FE/src/components/planner/month/MonthDetailInfo/GuestBook.tsx, FE/src/components/planner/month/MonthDetailInfo/Introduction.tsx, FE/src/components/planner/month/MonthFriends.tsx, FE/src/components/planner/week/list/WeekItem.tsx, FE/src/components/planner/week/list/WeekList.tsx, FE/src/components/planner/week/todo/WeekTodoItem.tsx, FE/src/pages/MyPage.tsx, FE/src/pages/Planner/MonthPage.tsx, FE/src/store/modalSlice.ts, FE/src/util/PrivateRoute.tsx, FE/src/util/TodoModule.ts
=> [FE] 소나큐브 코드 악취 수정

BE/src/main/java/com/newsainturtle/shadowmate/planner/enums/TodoStatus.java
=> [BE] 할일 진행중 상태 추가 

FE/src/components/planner/day/Ment.tsx, FE/src/pages/Planner/DayPage.tsx
close #579 
- 오늘의 회고 250자로 늘리기
- 내일의 다짐 100자로 늘리기
=> [FE] 오늘의 회고, 내일의 다짐 글자 수 늘리기

BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/response/AddDailyTodoResponse.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/response/DailyPlannerTodoResponse.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/response/TodoIndexResponse.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/response/WeeklyPlannerDailyTodoResponse.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/Todo.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/TodoRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/SearchPlannerServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/DailyPlannerServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/SearchPlannerServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/TimeTableRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/TodoRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/TodoRepositoryTest.java
close #583
- 할일 엔티티에 인덱스 필드 추가
- 할일 생성 로직
- 일일 플래너 조회 시 할일 인덱스 정렬 후 전달
=> [BE] 할일 순서 인덱스 생성

FE/src/api/Api.ts, FE/src/components/planner/day/todo/TimeTable.tsx, FE/src/components/planner/day/todo/TodoItem.tsx, FE/src/components/planner/day/todo/TodoItemChoice.tsx, FE/src/components/planner/day/todo/TodoList.tsx, FE/src/components/planner/week/list/WeekItem.tsx, FE/src/util/planner.interface.ts
close #581 
- 할 일 상태 세모 표시 추가
- 타임테이블 세모 상태도 등록 가능
(api 키값 변경으로 조회가 안되는 문제는 '할일 타임테이블 중복 표시' 이슈로 새로 파서 해결하겠습니다..)
=> [FE] 할 일 상태 세모 표시 추가

FE/src/components/mypage/MyPageFrame.tsx, FE/src/components/mypage/details/diary/Category.tsx, FE/src/components/mypage/details/diary/Dday.tsx
close #586 
- 카테고리, 디데이 글자수 변수화 
- 카테고리, 디데이 최소 글자수 변경 (2 -> 1)
=> [FE] 카테고리, 디데이 최소 글자수 변경

FE/src/components/planner/week/Week.tsx
close #576 
- 주별 플래너 깜빡임 원인 : loading을 넣어놓음 (내가 이걸 왜 넣었을까 ... 의도가 기억이 안남 🥲 )
- 그래서 loading 제거
=> [FE] 주별 플래너 깜빡임 수정

BE/src/main/java/com/newsainturtle/shadowmate/planner/constant/PlannerConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/controller/PlannerController.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/request/ChangeDailyTodoSequenceRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/response/AddDailyTodoResponse.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/response/DailyPlannerTodoResponse.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/dto/response/WeeklyPlannerDailyTodoResponse.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/Todo.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/TodoRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerService.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/SearchPlannerServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/DailyPlannerServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/PlannerControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/TodoRepositoryTest.java
close #584
- 할일 인덱스는 프론트에 전달하지 않는 걸로 변경했습니다😀
- 프론트에서 할일 인덱스 대신 아이디 값으로 전달해주시면 됩니다!
=> [BE] 할일 순서 변경 API 작성

FE/src/styles/planner/Month.module.scss
close #570 
- 캘린더 스크롤 생성
- 캘린더 방명록 최소 높이 설정
=> [FE] 캘린더 스크롤 생성

FE/src/components/common/Header/Menu.tsx, FE/src/components/common/Header/index.tsx, FE/src/components/common/Profile/index.tsx
close #589 
- 설정 버튼 생성
- 프로필에서 설정으로 이동하는 연결 제거
=> [FE] 설정 버튼 생성

FE/src/components/planner/month/Month.tsx, FE/src/components/planner/month/MonthCalendar.tsx, FE/src/components/planner/month/MonthGraph.tsx, FE/src/styles/planner/Month.module.scss, FE/src/util/colors.ts
close #582 
- 캘린더 statusColor 변수 분리 (@util/colors에 변수 넣었는데, 문제가 있다면 알려주세요 ! )
- 캘린더 그래프 생성 및 표시 (비공개 계정인 경우 미표시)
=> [FE] 캘린더 그래프 표시

BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/DailyPlannerServiceTest.java
close #600
- 타임테이블 삭제 코드 구현에서 실수가 있었습니다😭
- 더욱 꼼꼼하게 확인하겠습니다.. 죄송해요!🍎🫶
=> [BE] 타임테이블 삭제 로직 수정

BE/src/main/java/com/newsainturtle/shadowmate/auth/constant/AuthConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/auth/controller/AuthController.java, BE/src/main/java/com/newsainturtle/shadowmate/auth/dto/ChangeTokenRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/auth/exception/AuthErrorResult.java, BE/src/main/java/com/newsainturtle/shadowmate/auth/service/AuthService.java, BE/src/main/java/com/newsainturtle/shadowmate/auth/service/AuthServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/auth/service/RedisService.java, BE/src/main/java/com/newsainturtle/shadowmate/auth/service/RedisServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/config/jwt/JwtAuthenticationFilter.java, BE/src/main/java/com/newsainturtle/shadowmate/config/jwt/JwtAuthorizationFilter.java, BE/src/main/java/com/newsainturtle/shadowmate/config/jwt/JwtProvider.java, BE/src/main/java/com/newsainturtle/shadowmate/config/oauth/OAuth2LoginSuccessHandler.java, BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/auth/AuthServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/auth/AuthServiceTest.java
close #596
- 로그인 시 Refresh Token 발급
- Access Token 재발급 api 작성
=> [BE] JWT Refresh Token 발급

BE/src/main/java/com/newsainturtle/shadowmate/auth/constant/AuthConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/auth/controller/AuthController.java, BE/src/main/java/com/newsainturtle/shadowmate/auth/dto/RemoveTokenRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/auth/service/AuthService.java, BE/src/main/java/com/newsainturtle/shadowmate/auth/service/AuthServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/auth/service/RedisService.java, BE/src/main/java/com/newsainturtle/shadowmate/auth/service/RedisServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/config/SecurityConfig.java, BE/src/main/java/com/newsainturtle/shadowmate/config/jwt/JwtAuthenticationFilter.java, BE/src/main/java/com/newsainturtle/shadowmate/config/jwt/JwtAuthorizationFilter.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/auth/AuthControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/auth/AuthServiceTest.java
close #598
- 자동로그인 API 작성
- 로그아웃 API 작성
=> [BE] 자동로그인

BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/constant/PlannerSettingConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/controller/PlannerSettingController.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/dto/request/AddRoutineRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/dto/response/AddRoutineResponse.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/entity/Routine.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/entity/RoutineDay.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/entity/RoutineTodo.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/exception/PlannerSettingErrorResult.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/repository/RoutineDayRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/repository/RoutineRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/repository/RoutineTodoRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingService.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/RoutineDayRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/RoutineRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/RoutineTodoRepositoryTest.java
close #606
- 루틴 엔티티 정의
- 루틴 할일 엔티티 정의
- 루틴 요일 엔티티 정의
- 루틴 생성 API 작성
=> [BE] 루틴 생성 API 작성

BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/constant/PlannerSettingConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/controller/PlannerSettingController.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/dto/response/GetRoutineListResponse.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/dto/response/GetRoutineResponse.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/repository/RoutineDayRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/repository/RoutineRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingService.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/RoutineDayRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/RoutineRepositoryTest.java
=> [BE] 루틴 조회 API 작성

BE/src/main/java/com/newsainturtle/shadowmate/planner/service/SearchPlannerServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/entity/RoutineTodo.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/repository/RoutineTodoRepository.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/SearchPlannerServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/RoutineTodoRepositoryTest.java
close #614
- 일일 플래너와 주간 플래너 조회 시 할일로 생성되지 않은 루틴들 확인해서 할일에 추가했습니다!😀
=> [BE] 플래너 조회 시 루틴을 할일로 등록

BE/src/main/java/com/newsainturtle/shadowmate/planner/service/SearchPlannerServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/repository/RoutineTodoRepository.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/SearchPlannerServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/RoutineTodoRepositoryTest.java
close #615
- 캘린더 통계 조회 시 할일로 만들어지지 않은 루틴들도 카운트했습니다~~👀
=> [BE] 캘린더 조회 시 루틴 카운트

BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/dto/response/GetRoutineResponse.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingServiceImpl.java
=> [BE] 루틴 목록 조회 시 응답값에 카테고리 추가

FE/src/components/mypage/MyPageFrame.tsx, FE/src/components/mypage/MyPageTab.tsx, FE/src/components/mypage/details/diary/Category.tsx, FE/src/components/mypage/details/diary/Routine.tsx, FE/src/components/mypage/item/CategoryItem.tsx, FE/src/components/mypage/item/DdayItem.tsx, FE/src/components/mypage/item/RoutineItem.tsx, FE/src/components/mypage/list/CategoryList.tsx, FE/src/components/mypage/list/DdayList.tsx, FE/src/components/mypage/list/RoutineList.tsx, FE/src/hooks/configStore.ts, FE/src/pages/MyPage.tsx, FE/src/store/mypage/routineSlice.ts, FE/src/styles/mypage/MyPage.module.scss, FE/src/util/planner.interface.ts
close #620 
- redux routineSlice 생성
- 루틴 컴포넌트 생성
- 마이페이지 컴포넌트 파일명 변경 (접두 MyPage 삭제)
- 캘린더는 라이브러리 병합 후 연결하겠습니다 ~ 😃
- API 연결 후 주석 삭제 예정
=> [FE] 루틴 컴포넌트 생성

FE/src/App.tsx, FE/src/api/Api.ts, FE/src/api/BaseUrl.ts, FE/src/api/JsonAxios.ts, FE/src/components/auth/login/Login.tsx, FE/src/components/common/Profile/index.tsx, FE/src/hooks/configStore.ts, FE/src/store/authSlice.ts
close #609 
- redux local -> sessionStorage에 저장하도록 변경
- 자동로그인 체크 후 로그인 시, localStorage에 자동로그인 key 저장
- 페이지 종료 후 다시 접속 시, App.tsx에서  localStorage에 저장된 key 확인 후 자동로그인 API 전송, 헤더에 담긴 정보 redux에 저장
- 로그아웃 시 localStorage에 있는 key 삭제
=> [FE] 자동로그인 API 연결

FE/src/api/Api.ts, FE/src/api/BaseUrl.ts, FE/src/components/mypage/details/diary/Routine.tsx, FE/src/components/mypage/item/RoutineItem.tsx, FE/src/components/mypage/list/RoutineList.tsx, FE/src/pages/MyPage.tsx, FE/src/pages/Planner/MonthPage.tsx, FE/src/store/mypage/routineSlice.ts, FE/src/util/planner.interface.ts
=> [FE] 루틴 조회 API 연결

FE/src/App.tsx, FE/src/api/Api.ts, FE/src/api/BaseUrl.ts, FE/src/api/JsonAxios.ts, FE/src/components/common/Profile/index.tsx, FE/src/components/mypage/details/myInfo/CancelMembership.tsx, FE/src/store/authSlice.ts
close #619 
- 로그아웃 API 연결 
- 토큰 만료, 회원 탈퇴 시 로그아웃 API 연결
=> [FE] 로그아웃 API 연결

BE/src/main/java/com/newsainturtle/shadowmate/user/repository/UserRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserServiceTest.java
close #637
- 회원탈퇴 시 회원 권한 비공개 처리
- 회원탈퇴 시 소셜 비공개 처리
- 회원탈퇴 레포지토리 테스트 코드 작성
=> [BE] 회원탈퇴 시 로직 수정

FE/src/App.tsx, FE/src/api/Api.ts, FE/src/api/JsonAxios.ts
close #640 
- 자동로그인 에러 수정: 자동로그인 api에 headers 추가
- 토큰 갱신 에러 수정: `Bearer` 키워드 추가
=> [FE] 자동로그인 및 토큰 갱신 에러 수정

FE/src/components/common/Modal/RoutineUpdateModal.tsx, FE/src/components/mypage/MyPageFrame.tsx
close #645 
- 루틴 수정 및 삭제 모달 컴포넌트 생성 (+selector)
- 루틴 수정 및 삭제 모달 열리고/닫히는 로직 생성 
- API 연결은 루틴 등록 API 연결되고 해야 할듯 .. 충돌이 무서워 요 ~~
=> [FE] 루틴 수정 및 삭제 모달 컴포넌트 생성

FE/src/api/Api.ts, FE/src/components/mypage/MyPageDetail.tsx, FE/src/components/mypage/MyPageFrame.tsx, FE/src/components/mypage/details/diary/Routine.tsx
close #647 
- 루틴 수정/삭제 API 생성
- 루틴 수정/삭제 API 연결
=> [FE] 루틴 수정, 삭제 API 연결

BE/src/main/java/com/newsainturtle/shadowmate/follow/entity/Follow.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/entity/FollowRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/repository/FollowRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/repository/FollowRequestRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/SearchPlannerServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/repository/FollowRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/repository/FollowRequestRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/SearchPlannerServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/FollowRequestRepositoryTest.java
close #653
- User 객체 변수명에 `Id`를 제거했습니다😀
=> [BE] 팔로우 엔티티 리팩토링

FE/src/api/Api.ts, FE/src/api/BaseUrl.ts, FE/src/components/planner/day/todo/TodoItem.tsx, FE/src/components/planner/day/todo/TodoItemChoice.tsx, FE/src/components/planner/day/todo/TodoList.tsx, FE/src/components/planner/week/list/WeekItem.tsx, FE/src/styles/planner/day.module.scss, FE/src/util/DragModule.ts
close #
- 할일 순서 변경 API 추가
- 드래그 이동 로직 추가(src/util/DragModule.ts)
- 일별 플래너 드래그 이동 적용
=> [FE] 할일 드래그 이동 로직 추가 및 일별 플래너 적용

BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/DailyPlannerLikeRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/SearchPlannerServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/DailyPlannerServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/SearchPlannerServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/DailyPlannerLikeRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/PlannerSettingServiceTest.java
#655
- 하나의 메소드에서 너무 많은 로직이 있어서, 가독성 문제가 있었습니다.( ߹꒳߹ )
- 일부 로직을 메소드로 분리하였습니다!
=> [BE] 코드스멜 리팩토링

FE/src/components/common/CategorySelector/index.tsx, FE/src/components/common/Modal/mypage/NewItemContainer.tsx, FE/src/components/mypage/MyPageDetail.tsx, FE/src/components/mypage/MyPageFrame.tsx, FE/src/components/mypage/MyPageList.tsx, FE/src/components/mypage/details/diary/Category.tsx, FE/src/components/mypage/details/diary/Dday.tsx, FE/src/components/mypage/details/diary/Routine.tsx, FE/src/components/mypage/item/RoutineItem.tsx, FE/src/components/planner/day/todo/TodoItem.tsx, FE/src/components/planner/week/list/WeekItem.tsx, FE/src/store/mypage/categorySlice.ts, FE/src/store/mypage/ddaySlice.ts, FE/src/store/mypage/routineSlice.ts, FE/src/styles/common/Modal.module.scss, FE/src/styles/mypage/MyPage.module.scss
close #649 
주 변경 내용
- 마이페이지 카테고리/디데이/루틴 생성 시 공통 모달 사용으로 변경
부 변경 내용
- 루틴 에러 변수 -> 객체로 변경
- 카테고리/디데이/루틴 마운트 시 커서 위치를 타이틀로 이동
- 루틴 반복 요일 CSS 변경 및 에러 CSS 변경
=> [FE] 마이페이지 루틴 설정 로직 리팩토링

FE/src/App.tsx
close #661 
- 새로고침 시 캘린더로 이동하는 에러 -> 자동로그인 시 로그인 여부 조건 설정
=> [FE] 새로고침 시 캘린더로 이동하는 에러 수정

BE/src/main/java/com/newsainturtle/shadowmate/auth/service/AuthServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/config/auth/PrincipalDetailsService.java, BE/src/main/java/com/newsainturtle/shadowmate/config/oauth/PrincipalOauth2UserService.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/repository/VisitorBookRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/social/service/SocialServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/user/controller/UserController.java, BE/src/main/java/com/newsainturtle/shadowmate/user/repository/UserRepository.java, BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserService.java, BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/auth/AuthServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/auth/UserRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner/repository/VisitorBookRepositoryTest.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/social/SocialServiceTest.java
close #663
- 회원탈퇴 시 본인이 작성한 방명록 삭제, 닉네임 변경 (사용자들이 사용할 수 없는 11~19자리 닉네임으로 변경)
- 탈퇴한 회원을 조회할 수 없도록 로직 수정
- 로직 간소화, 사용하지 않은 메소드 삭제
=> [BE] 회원탈퇴 관련 로직 수정

BE/src/main/java/com/newsainturtle/shadowmate/follow/entity/Follow.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/entity/FollowRequest.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/DailyPlanner.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/DailyPlannerLike.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/TimeTable.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/Todo.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/VisitorBook.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/Weekly.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/entity/WeeklyTodo.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/entity/Category.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/entity/Dday.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/entity/RoutineTodo.java, BE/src/main/java/com/newsainturtle/shadowmate/social/entity/Social.java, BE/src/test/java/com/newsainturtle/shadowmate/yn/planner_setting/repository/SocialRepositoryTest.java
close #666
- 데이터베이스 테이블 제약조건을 좀 더 자세하게 설정하였습니다😀
- 서버 DB는 변경 완료한 상태입니다!
=> [BE] 엔티티 제약조건 변경

FE/src/components/auth/login/Login.tsx, FE/src/components/common/Header/index.tsx, FE/src/styles/common/DataRangePicker.css
close #652 
- 설문 팝업 보이지 않기
- 추후에 팝업 재사용을 위해 주석 처리로 열리지 않게만 했습니다. 
- 헤더에 설문 → 문의 버튼으로 변경
=> [FE] 설문 팝업 감추기 & 헤더 문의 버튼으로 변경

FE/src/components/planner/day/todo/TodoItem.tsx, FE/src/components/planner/day/todo/TodoList.tsx, FE/src/util/TodoModule.ts
close #659 
- util/todoModule 일부 수정
- 할 일 삭제시 map.filter에서 copyTodos[idx]로 삭제하는 것으로 수정
- 일별 플래너 util/todoModule로 적용 리팩토링
- 일별 일부 변수명 주별과 일치하게 리팩토링
=> [FE] 일별 플래너 리팩토링

FE/src/components/planner/week/list/WeekItem.tsx, FE/src/components/planner/week/list/WeekItemInput.tsx, FE/src/components/planner/week/list/WeekList.tsx, FE/src/components/planner/week/todo/WeekTodo.tsx, FE/src/styles/planner/Week.module.scss
close #660 
- 주별 플래너 할 일 순서 변경 로직 추가
=> [FE] 주별 플래너 할 일 순서 변경

FE/src/components/auth/login/Login.tsx
=> [FE] 로그인 시 엔터 동작 추가

FE/src/components/mypage/MyPageFrame.tsx, FE/src/components/mypage/details/diary/Category.tsx, FE/src/components/mypage/details/diary/Dday.tsx, FE/src/components/mypage/details/diary/Routine.tsx, FE/src/styles/mypage/MyPage.module.scss
close #671 
- 루틴 카테고리 커서 변경
- 루틴 반복 기간 '~' 추가
- 마이페이지 상세 설정 스크롤 설정
- 루틴 목록 - 아이템 min-height, padding 설정 (루틴 이름이 길어지는 경우 높이 늘어남)
=> [FE] 마이페이지 변경사항 반영

FE/src/components/planner/week/list/WeekItem.tsx, FE/src/components/planner/week/list/WeekItemInput.tsx, FE/src/components/planner/week/todo/WeekTodoInput.tsx, FE/src/components/planner/week/todo/WeekTodoItem.tsx
close #678 
- 주별 플래너 글자수 제한 설정
=> [FE] 주별 플래너 글자수 에러 수정

FE/src/components/auth/login/Login.tsx, FE/src/components/auth/signup/SignupAccount.tsx, FE/src/components/common/Input/index.tsx, FE/src/components/mypage/details/diary/Category.tsx, FE/src/components/mypage/details/diary/Dday.tsx, FE/src/components/mypage/details/diary/Routine.tsx, FE/src/components/mypage/details/friend/MyFriendFrame.tsx, FE/src/components/mypage/details/myInfo/MyInfo.tsx, FE/src/components/mypage/details/myInfo/MyPassword.tsx, FE/src/components/social/SocialInput.tsx
close #677
- 모든 입력 인풋에 글자수를 제한
=> [FE] 입력 글자수 제한 적용

FE/src/components/mypage/MyPageFrame.tsx, FE/src/components/mypage/details/diary/Category.tsx, FE/src/components/mypage/details/diary/Dday.tsx, FE/src/components/mypage/details/diary/Routine.tsx, FE/src/styles/mypage/MyPage.module.scss
close #681 
- 마이페이지 카테고리/디데이/루틴 삭제 에러 수정
- 디데이 min-height 설정
=> [FE] 마이페이지 카테고리/디데이/루틴 삭제 에러 수정 및 디데이 min-height 설정

README.md
=> [공통] 버전2 업데이트 내용 리드미에 추가

BE/src/main/java/com/newsainturtle/shadowmate/follow/constant/FollowConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/controller/FollowController.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/dto/response/SearchUserResponse.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/exception/FollowErrorResult.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowService.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/service/FollowServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/service/UserFollowService.java, BE/src/main/java/com/newsainturtle/shadowmate/follow/service/UserFollowServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/user/constant/UserConstant.java, BE/src/main/java/com/newsainturtle/shadowmate/user/controller/UserController.java, BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserService.java, BE/src/main/java/com/newsainturtle/shadowmate/user/service/UserServiceImpl.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/FollowServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/follow/UserFollowServiceTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserControllerTest.java, BE/src/test/java/com/newsainturtle/shadowmate/kh/user/UserServiceTest.java
#696
- 각 서비스에서 너무 많은 레포지토리를 사용하고 있고, 중복되는 메소드도 보여서 리팩토링하고 있습니다!
- 각 서비스에서는 최소한의 레포지토리를 사용하고, 상위 서비스를 만들어서 각 서비스의 코드를 재활용할 수 있도록 수정했습니다.
- 현재는 팔로우와 유저 서비스의 의존도를 낮추는 작업을 진행한 코드입니다~~😀
=> [BE] 팔로우와 유저 서비스 간 의존성 제거

FE/cypress/e2e/login.cy.ts, FE/src/App.tsx, FE/src/components/auth/login/Login.tsx, FE/src/components/common/Input/index.tsx, FE/src/styles/auth/Login.module.scss
close #701 
- 로그인 테스트 코드 작성
- Mui 내 inputProps에 "data-cy" props 추가
- redux-persist 문법 에러 수정
=> [FE] 로그인 테스트 코드 작성

BE/src/main/java/com/newsainturtle/shadowmate/planner/service/DailyPlannerServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/MonthlyPlannerServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/planner/service/WeeklyPlannerServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/planner_setting/service/PlannerSettingServiceImpl.java, BE/src/main/java/com/newsainturtle/shadowmate/social/service/SocialServiceImpl.java
close #711
- 일부 서비스 코드를 람다로 리팩토링하였습니다!😀
=> [BE] 람다를 활용한 서비스 코드 리팩토링

FE/src/components/mypage/details/friend/MyFriend.tsx, FE/src/components/mypage/details/friend/MyFriendFrame.tsx, FE/src/styles/mypage/MyPage.module.scss
=> [FE] 팔로우 목록 스크롤

FE/cypress.config.ts, FE/cypress/e2e/signup.cy.ts, FE/src/components/auth/signup/Signup.tsx, FE/src/components/auth/signup/SignupAccount.tsx, FE/src/components/auth/signup/SignupContract.tsx
close #715 
- 회원 가입 페이지 테스트 코드를 작성했습니다.
- 약관 동의 테스트 코드도 작성했었으나, 회원 가입 쪽에서는 회원 정보 입력 테스트에 집중하는게 좋을 것 같아서 전체 동의 후 회원 정보 테스트만 작성하는 코드로 커밋했습니다.
- 약관 동의와 회원 정보 입력 페이지가 하나의 링크로 되어있어서 만약 약관 동의 테스트 코드를 추가하고 싶다면 파일을 분리해서 별도로 작성하는게 좋지 않을까 싶습니다...🤣 (필요하다면 커밋 기록 남은걸로 보고 쓰시면 될 것 같아요)
=> [FE] 회원가입 테스트 코드 작성
